### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by SharhaSimona** [ShargaSimona/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Sdot13** [comment]
Jacques Payet - is a practitioner of Yoshinkan-style aikido. He was the longest-serving non-Japanese uchi-deshi of Yoshinkan founder Gozo Shioda and is ranked Hachidan (八段, "8th degree") in the Yoshinkan organization, with the honorific Shihan (師範, "mentor and model").[1] He is the founder and head instructor of Mugenjuku dojo and the Mugenjuku Kenshusei program in Kyoto, Japan. He is also the originator of the well-known Senshusei Course, a translator of several important works in aikido, and a guest instructor in demand around the world.

**Comment by Sdot13** [comment]
`I'm a newcomer to the world of IT, but my passions are perfection and attention to details, so that's why I improving my QA / QC skills.`
