### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by SharhaSimona** [ShargaSimona/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Sdot13** [comment]
1. FB: https://www.facebook.com/profile.php?id=100005462621764
2. mail: shargasimona@gmail.com
3. skype: Simona Sharga
4. git: https://github.com/ShargaSimona
5. tel:380508825067
