### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by SharhaSimona** [ShargaSimona/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Sdot13** [comment]
CHARACTER
problem-solving
communication
multitasking
responsible
attentive to details


EDUCATION
Every day
QA testing Python

March 2021
Software Testing Masterclass at Udemy
6st November 2020 – 26th January 2021
Quality Control Technology/Technician at Tommy Univer
2009 – 2014
Psychology, philosophical faculty. Specialist at University Ivan Franko National University of Lviv
ARTICLES
None published yet
