### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by SharhaSimona** [ShargaSimona/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Sdot13** [comment]
LIKES😃
music
book
snowboard and skiing
nature
cats and dogs
movies and series
attention to details

DISLIKES😞
incompetence
anger
disrespect
cigarette smoke
disorder

WANTS🥺
TO BE HEALTHY BE INDEPENDENT READ MORE TO BUY A CARTO BE BRAVE TO BECOME A SUPERHERO TO LISTEN AND LEARN
